### ISSUE TITLE
npm上的midwayjs-knife4j2包不存在，猜测是写错了包名

### ISSUE THREAD

**Issue by hillsonziqiu** [fangbao-0418/midway#2]
midwayjs-knife4j2 老哥，这个包在npm上找不到, midwayjs-kinfe4j2 这个是正确的包。我想问是不是上传npm的时候名字写错了。

**Comment by IceSakuraAzure** [comment]
我就说咋找不到.....npm的名写错了

**Comment by fangbao-0418** [comment]
确实写错了，midwayjs-knife4j2可用了
